# Fundamentals of Python programming

If you know how to program in Python, this section of the exercises is not for you. Close this cell and do the next one.

Here, we are going to discuss the most basic aspects of programming that you are going to need to understand to code all necessary steps to train a model using PyTorch.

## Concepts


### Variables

A variable is something you define in your code with a name:

In [ ]:
from torch.distributed.tensor import randn

x = 2
float_number = 3.14
my_name = "Ryland Grace"

First comes the name of the variable, then what you assign to it. Python is pretty flexible when defining variables of different type: integer, float, strings, etc.

### Lists

You can define lists of variables too:

In [11]:
integers = [1, 2, 3, 4]
floats = [1.2, 2.3, 3.4]
numbers = [1, 1.2, 3.4, 5]
strings_and_numbers = ["Hello", 2, 4, "Bye"]

Again, Python is very flexible with these. We would recommend that you stick to the same type of variable of all elements in a list. You can access their elements with indexing (first element will always have index 0, not 1):

In [12]:
print(strings_and_numbers[0])

Hello


### Conditionals

We can use conditions in our code to run certain commands depending on whether if the input meets certain criteria.

In [3]:
distance = 5000

if distance > 2500:
  print("We are safe!")
else:
  print("We are going to crash!")

We are safe!


In [4]:
animal = "cat"

if animal == "dog":
  print("I love dogs!")
elif animal == "cat":
  print("I am alergic to cats.")
else:
  print("I don't know this animal.")

I am alergic to cats.


### Loops

We use loops when there is an operation that we have to repeat.

In [5]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
names = ["Ryland Grace from Earth", "Rocky from Erid"]
for name in names:
  print(hello(name))

Hello, Ryland Grace from Earth!
Hello, Rocky from Erid!


### Function

A function is a piece of code that receives some arguments and returns a value:

In [1]:
# You can define the types of the arguments and the return value
def simple_sum(a: int, b: int) -> int:
  return a + b

print(simple_sum(2, 3))

5


In [2]:
def hello(name):
  return "Hello, " + name + "!"

print(hello("Ryland"))

Hello, Ryland!


We use functions when there is a piece of code that we want to use several times, so that we do not have to repeat the code used.

### Class

Python is an object-oriented language, which allows us to structure the code using classes and objects for better organization and reusability.

For example, a class could be Animal and an object of that class would be dog. In a class, you have the `__init__` method, that allows you to initialize an object given a set of parameters. With those parameters, you initialize the internal *attributes* of the class, e.g., `self.something`. You can also define internal methods for the class, which are functions you can call if you have declared an object of that class.

In [7]:
class Animal:
  def __init__(self, name, legs, sound):
    # Initialization of internal parameters
    self.name = name
    self.legs = legs
    self.sound = sound

  def make_sound(self):
    return self.sound + "!"


To access the attributes or methods, you can just call them after using a dot on the declared object.

In [11]:
dog = Animal("perro", 3.5, "auu")
print(dog.name)
print(dog.legs)
print(dog.make_sound() )

perro
3.5
auu!


## Exercises



### Variables

1. Create variables for `bill_amount` and `tip_percentage`. Calculate the total bill and print a message like: "Your total is $115.00".

In [12]:
bill_amount = 100
tip_percentage = 0.15

print(f"Your total is ${bill_amount * (1 + tip_percentage):.2f}")

Your total is $115.00


2. Assign `a = 5` and `b = 10`. Without manually typing the numbers again, write code that swaps their values so `a` becomes 10 and `b` becomes 5.

In [14]:
a = 5
b = 10

new_a = b
new_b = a

print(f"The new value of a is {new_a} and the new value of b is {new_b}")
# Do your code here...

The new value of a is 10 and the new value of b is 5


3. Create variables for your name, age, and favorite hobby. Use an f-string to print a sentence: "Hi, I'm Alex, I'm 25, and I love coding"

In [15]:
name = "Eduardo"
age= 27
hobby = "Dodgeball"

print(f"Hi, I'm {name}, I'm {age}, and I love {hobby}")

Hi, I'm Eduardo, I'm 27, and I love Dodgeball


### Lists

1. Create a list of three items. Use `.append()` to add a fourth item, then use `del` or `.remove()` to take the second item off the list.

**Note**: if you do not know what these methods do, look it up on the Internet.

In [20]:
list = ["Patatas", 3 , "elemento"]

list.append("mermelada")

print(list)

del list[2]
print(list)

['Patatas', 3, 'elemento', 'mermelada']
['Patatas', 3, 'mermelada']


2. Create a list of five names. Print the first name and the last name using indexing.

In [21]:
names = ["Alice", "Bob", "Charlie", "David", "Eve"]

print(f"The first name is {names[0]} and the last name is {names[-1]}")

The first name is Alice and the last name is Eve


3. Create a list of five integers. Use Python's built-in functions to print the `sum()`, the `max()`, and the `len()` of the list.

In [23]:
list = [1, 2, 3, 4, 5]

print(sum(list))
print(max(list))
print(len(list))

15
5
5


### Conditionals

1. Write a program that takes a numerical score (0-100) and prints the corresponding grade:
- "Excellent" if 90 or above
- "Normal" if between 80 and 89
- "Good" if between 60 and 79
- "Sufficient" if between 50 and 69
- "Insufficient" if below 50.

In [32]:
import random

score = random.randint(0, 100)
print(score)

if score >= 90:
    print("Excellent")
elif score >= 80:
    print("Normal")
elif score >= 60:
    print("Good")
elif score >= 50:
    print("Sufficient")
else:
    print("Insufficient")

99
Excellent


2. Create a variable `stored_password` and set it to a string of your choice. Then, create a variable `user_input`.
- If the input matches the password, print "Access granted!".
- If the input is an empty string, print "Please enter password".
- Otherwise, print "Access denied."

In [37]:
stored_password = "my_secret_password"

# Keep asking for password until a non-empty one is entered
while True:
    user_input = input("Enter your password: ")

    if user_input == "":
        print("Please enter password")
        continue  # Ask again
    elif user_input == stored_password:
        print("Access granted!")
        break  # Exit the loop on success
    else:
        print("Access denied.")
        break  # Exit the loop on wrong password

Please enter password
Please enter password
Access granted!


3. Write a script that decides the ticket price based on a person's age.
- If the person is under 5, the ticket is Free.
- If they are between 5 and 65, the ticket is \$15.
- If they are older, the ticket is \$10.

In [40]:

# Keep asking for person's age until a non-empty one is entered
while True:
    person_age = int(input("Enter your age: "))

    if person_age == "":
        print("Please enter password")
        continue  # Ask again
    elif person_age < 5:
        print("The ticket is Free.")
        break  # Exit the loop on success
    elif person_age <= 65:
        print("The ticket is $15.")
        break  # Exit the loop on success
    else:
        print("The ticket is $10")
        break  # Exit the loop on success

The ticket is $15.


### Loops

1. Use a while loop to print the numbers from 10 down to 1, followed by "Blast off!"

In [41]:
i = 10

while i > 0:
    print(i)
    i -= 1

print("Blast off!")

10
9
8
7
6
5
4
3
2
1
Blast off!


2. Use a for loop to iterate through a list of numbers and print the square of each number.

In [44]:
numbers = [1, 2, 3, 4, 5]
for i in numbers:
    print(i)
    print(i ** 2)

1
1
2
4
3
9
4
16
5
25


3. Create a list of colors. Use a for loop to check each color; if the color is "Green", print "Found it!" and use the break keyword to stop the loop.

In [48]:
colours = ["Red", "Blue", "Green", "Yellow"]

for colour in colours:
    if colour == "Green":
        print("Found it!")
        print(colour)
        break

Found it!
Green


### Functions

1. Write a function called `greet_user(name)` that takes a string and prints a greeting to the user.

In [50]:
def greet_user(name):
    print(f"Hello, {name}!")

greet_user(input("Enter your name: "))

Hello, Eduardo!


2. Write a function that accepts `length` and `width` as arguments and returns the area of a rectangle.

In [51]:
def calculate_area(length, width):
    return length * width

calculate_area(2,2)

4

3. Create a function that takes a number and returns `True` if it is even and `False` if it is odd.

**Hint**: use the modulo `%` operator.


In [53]:
def is_even(number):
    return number % 2 == 0
is_even(76)

True

### Classes and objects

1. Create a `Book` class with an `__init__` method that stores the title and the author. Create two different instances from this class.

In [54]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author
book1 = Book("The Great Gatsby", "F. Scott Fitzgerald")
book2 = Book("To Kill a Mockingbird", "Harper Lee")
print(f"Book 1: {book1.title} by {book1.author}")
print(f"Book 2: {book2.title} by {book2.author}")

Book 1: The Great Gatsby by F. Scott Fitzgerald
Book 2: To Kill a Mockingbird by Harper Lee


2. Create a `BankAccount` class with a `balance` attribute. Add a method `deposit(amount)` that adds to the balance and a method `withdraw(amount)` that subtracts from it.

In [66]:
class BankAccount:
    def __init__(self):
        self.balance = 15

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds")
        else:
            self.balance -= amount

account = BankAccount()
account.deposit(100)
print(f"Balance after deposit: ${account.balance}")
account.withdraw(30)
print(f"Balance after withdrawal: ${account.balance}")
account.withdraw(80)  # This should print "Insufficient funds"

print(f"${account.balance}")

Balance after deposit: $115
Balance after withdrawal: $85
$5


# PyTorch Fundamentals: the Deep Learning library

In this section we are going to work on the basics of PyTorch, the Deep Learning library we are going to use in this course. We will work on the things covered in the first session, to drive home some of the concepts we have worked on.

## Concepts

### Tensors: The building blocks of PyTorch





A tensor is a multi-dimensional array that can be used to store data. It is the fundamental building block of PyTorch, and it is used to represent the input data, the parameters of the model, and the output of the model. Tensors can be of different types, such as `torch.FloatTensor`, `torch.IntTensor`, etc., depending on the type of data they store. We can perform various operations on tensors, such as addition, multiplication, etc. They allow us to perform operations parallelly on the GPU, on all the elements of the tensor at the same time, or between tensors if they have the same shape. This is what makes PyTorch so powerful for Deep Learning, as it allows us to perform operations on large amounts of data efficiently.

In [3]:
import torch

# Create a tensor of size (2, 3) filled with random values
tensor_1 = torch.randn(2, 3)
print(tensor_1)

tensor([[ 1.0190, -1.1333, -1.0243],
        [ 0.6409, -0.9880, -0.8622]])


In [58]:
# Create a tensor of size (2, 3) with the values [[1, 2, 3], [4, 5, 6]]
tensor_2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor_2)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [59]:
# Sum of two tensors
print(tensor_1 + tensor_2)

tensor([[2.3253, 2.8223, 3.3229],
        [4.5180, 5.3829, 6.9371]])


In [60]:
# Multiplication of two tensors
print(tensor_1 * tensor_2)

tensor([[1.3253, 1.6447, 0.9688],
        [2.0721, 1.9145, 5.6226]])


### Defining the Architecture: The `nn.Module` class

In Python, we can have inheritance relationships between classes. A class that inherits from another class is called a child class, and the class that is inherited from is called a parent class. The child class can use all the methods and attributes of the parent class, and it can also have its own methods and attributes.

In PyTorch, we define the architecture of a model by creating a child class of `nn.Module`, which is the parent class that contains all the necessary methods and attributes to work with PyTorch. In this child class, we have to define the `__init__` method, where we initialize the layers of the model, and the `forward` method, where we define how the input data flows through the layers to produce the output.

In [14]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.layer1 = nn.Linear(10, 5)
    self.layer2 = nn.Linear(5, 1)

  def forward(self, x):
    x = self.layer1(x)
    x = torch.relu(x)
    x = self.layer2(x)

    return x

model = MyModel()

In [16]:
vector = torch.randn(10)  # Random input vector of size 10
print(vector)
output = model(vector)
print(output)


tensor([-1.9554, -2.4901,  3.2580,  0.1424, -0.8571,  0.1229,  0.6646,  0.4876,
         2.2475,  0.4029])
tensor([-0.1886], grad_fn=<ViewBackward0>)


Using PyTorch, we can separate the layers from the activation functions, which gives us more flexibility to define the architecture of the model. In the example above, we have defined just two layers (`layer1` receives an input of size 10 and produces an output of size 5, and `layer2` receives an input of size 5 and produces an output of size 1), and we have used the ReLU activation function between them. We can easily change the architecture by adding more layers or using different activation functions.

### The Loss Function

The loss function is a measure of how well the model is performing. It takes the output of the model and the true labels, and it returns a single value that represents the error of the model.

PyTorch has a lot of built-in loss functions that we can use, such as `nn.MSELoss` for regression problems and `nn.CrossEntropyLoss` for classification problems. We can also define our own custom loss functions if we need to. If that is the case, they also inherit from `nn.Module` and we have to define the `forward` method, where we calculate the loss given the output of the model and the true labels.

In [17]:
import torch.nn as nn

mse_loss = nn.MSELoss()
input = torch.tensor([0.0, 0.0, 0.0, 0.0])
output = torch.tensor([1.0, 1.0, 1.0, 1.0])
loss = mse_loss(input, output)
print(loss)

tensor(1.)


In [18]:
class CustomLoss(nn.Module):
  def __init__(self):
    super(CustomLoss, self).__init__()

  def forward(self, input, output):
    return torch.sum((input - output) ** 2) / input.size(0)  # This is just an example, another MSE loss

custom_loss = CustomLoss()
loss = custom_loss(input, output)
print(loss)

tensor(1.)


### The Training Loop

As we have seen in the lecture, the gradient descent can be programmed in a loop, since we have to update the weights of the model several times until we reach a good performance. The training loop consists of the following steps:
1. Forward pass: we pass the input data through the model to get the output.
2. Calculate the loss: we calculate the loss using the output of the model and the true labels.
3. Backward pass: we calculate the gradients of the loss with respect to the parameters of the model using backpropagation.
4. Update the weights: we update the weights of the model using the gradients calculated in the backward pass and an optimization algorithm, such as Stochastic Gradient Descent (SGD) or Adam (we will see these in the next session).

PyTorch does all of these steps for us, so we just have to write the code to call the necessary methods and functions.

In [82]:
import torch

model = MyModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):  # Loop over the dataset multiple times
    # Forward pass
    output = model(vector)

    # Calculate the loss
    loss = criterion(output, output)  # This is just an example, we should use the true labels instead of the output

    # Backward pass
    optimizer.zero_grad()  # Zero the gradients before backward pass
    loss.backward()  # Compute the gradients

    # Update the weights
    optimizer.step()  # Update the weights using the gradients

## Exercises

### Defining the Architecture: The `nn.Module` class

1. Write a class for a simple MLP that receives an input of size 4, has a hidden layer of size 8, and produces an output of size 2.

In [20]:
class SimpleMLP(nn.Module):
  def __init__(self):
    super(SimpleMLP, self).__init__()
    self.layer1 = nn.Linear(4, 8)
    self.layer2 = nn.Linear(8, 2)

  def forward(self, x):
    x = self.layer1(x)
    x = torch.relu(x)
    x = self.layer2(x)
    return x

tensor = torch.randn(4)  # Random input vector of size 4
model = SimpleMLP()
output = model(tensor)
print(output)  # This should print a tensor of size 2

tensor([-0.6371,  0.5486], grad_fn=<ViewBackward0>)


2. This is a single-layer perceptron. Use an activation function of your choice to make it a non-linear model. See how the output changes with and without the activation function.

In [21]:
class SingleLayerPerceptron(nn.Module):
  def __init__(self):
    super(SingleLayerPerceptron, self).__init__()
    self.layer = nn.Linear(4, 2)

  def forward(self, x):
    x = self.layer(x)
    x = torch.sigmoid(x)
    return x

tensor = torch.randn(4)  # Random input vector of size 4
model = SingleLayerPerceptron()
output = model(tensor)
print(output)

tensor([0.3929, 0.5647], grad_fn=<SigmoidBackward0>)


3. We can see the model deeply by printing it. We can also print the parameters of the model. Try to understand what each parameter is and how it is related to the layers of the model.

In [22]:
model = MyModel()
print(model)  # This will print the architecture of the model
print(list(model.parameters()))  # This will print the parameters of the model

MyModel(
  (layer1): Linear(in_features=10, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=1, bias=True)
)
[Parameter containing:
tensor([[-0.1692,  0.2913,  0.2342, -0.2207, -0.0012, -0.0207,  0.2688,  0.0578,
          0.1472, -0.0725],
        [ 0.2702, -0.2832,  0.0585,  0.0310, -0.1948,  0.2312,  0.1057, -0.0588,
          0.0800,  0.1877],
        [-0.2328, -0.0288,  0.0658,  0.1962,  0.0331,  0.3001,  0.2120, -0.1733,
          0.1653, -0.2992],
        [-0.0333,  0.1414,  0.0844, -0.2757,  0.2916,  0.0415, -0.0047,  0.3052,
         -0.1187, -0.1041],
        [-0.0255, -0.0447,  0.1323, -0.0280, -0.2156,  0.2583, -0.0491, -0.1763,
          0.2929,  0.2653]], requires_grad=True), Parameter containing:
tensor([0.0387, 0.2625, 0.2270, 0.2875, 0.0639], requires_grad=True), Parameter containing:
tensor([[ 0.2022, -0.1964, -0.1989,  0.0676,  0.0698]], requires_grad=True), Parameter containing:
tensor([-0.0162], requires_grad=True)]


### The Loss Function

1. Create a custom loss function that calculates the mean absolute error (MAE) between the output of the model and the true labels.

**Hint**: the torch library has built-in functions for both mean and absolute value, so you can use them to calculate the MAE.

In [9]:
class MAELoss(nn.Module):
  def __init__(self):
    super(MAELoss, self).__init__()

  def forward(self, input, output):
    return torch.mean(torch.abs(input - output))

2. We have two problems at hand: in one of them, we have to predict the temperature of a city given some data other data from that same day (humidity, wind speed, etc.). In the other problem, we have to predict whether an email is spam or not given the text of the email. Look at the documentation of PyTorch for `nn.MSELoss` and `nn.CrossEntropyLoss` and decide which loss function is more appropriate for each problem.

Explain your reasoning here.

### The Training Loop

1. Which step is missing here? Can you fill in the blanks to complete the training loop? Explain what the missing step does.

In [10]:
model = MyModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):
    output = model(vector)

    loss = criterion(output, output)

    optimizer.zero_grad()
    loss.backward()  # Compute the gradients

    optimizer.step()

2. Check this out. What happened to the weights?

In [33]:
model = MyModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

input = torch.randn(10)
ground_truth = torch.randn(1)

print("Weight values before training: ")
print(list(model.parameters()))
for epoch in range(15):
    output = model(input)
    loss = criterion(output, ground_truth)
    print(loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("\nWeight values after training: ")
print(list(model.parameters()))

Weight values before training: 
[Parameter containing:
tensor([[-0.0434, -0.2814,  0.0777, -0.0284, -0.1947, -0.1579, -0.1330,  0.1892,
         -0.2545,  0.2002],
        [-0.1705, -0.1575,  0.0797, -0.1413,  0.2364,  0.0461,  0.0554,  0.0730,
         -0.0460, -0.1927],
        [-0.0817,  0.0072, -0.2495,  0.1531, -0.1730, -0.1531, -0.1066,  0.2104,
         -0.0127,  0.2030],
        [ 0.3143,  0.0652, -0.0882, -0.0646,  0.2390, -0.2500,  0.0476,  0.0748,
         -0.1432,  0.2695],
        [-0.1281, -0.1772,  0.0100, -0.2849,  0.2261,  0.2473, -0.0981, -0.0603,
          0.1884, -0.0412]], requires_grad=True), Parameter containing:
tensor([-0.2992,  0.2525, -0.1005, -0.0118,  0.1839], requires_grad=True), Parameter containing:
tensor([[-0.0028,  0.4219, -0.3360,  0.3150, -0.3783]], requires_grad=True), Parameter containing:
tensor([-0.2229], requires_grad=True)]
0.3859613835811615
0.29906392097473145
0.23204529285430908
0.18783003091812134
0.1584174782037735
0.1334390789270401
0.11